---
name: "jellyfin-plugin-playbackreporting"
guid: "5c534381-91a3-43cb-907a-35aa02eb9d2c"
version: "6"
jellyfin_version: "10.5.0"
owner: "jellyfin"
nicename: "Playback Reporting"
description: "Collect and show user play stats"
overview: "Collect and show user play stats"
category: "General"
artifacts:
  - "Jellyfin.Plugin.PlaybackReporting.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
